window.sr = ScrollReveal({ reset: true })
ScrollReveal({ distance: '20px' })
sr.reveal('.start', { duration: 2500, origin: 'left' })
sr.reveal('.mypicture', { duration: 2500, origin: 'right' })
sr.reveal('.picture', { duration: 2500, origin: 'left' })
sr.reveal('.about', { duration: 2500, origin: 'right' })
sr.reveal('.projects', { duration: 2500, origin: 'bottom' })
sr.reveal('.projects-itens', { duration: 2500, origin: 'bottom' })
sr.reveal('.github-projects', { duration: 2500, origin: 'bottom' })
sr.reveal('.skills', { duration: 2500, origin: 'bottom' })
sr.reveal('.icons', { duration: 2500, origin: 'bottom' })
sr.reveal('.text-description', { duration: 2500, origin: 'bottom' })
